server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location ~* \.(css|js)$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location ~* \.(jpg|jpeg|png|webp|svg)$ {
        add_header Cache-Control "public, max-age=86400";
    }

    location ~* \.(mp4|webm)$ {
        add_header Cache-Control "public, max-age=604800";
        mp4;
    }

    gzip on;
    gzip_types text/css application/javascript image/jpeg image/png;
}
